<?xml version="1.0" encoding="UTF-8"?>
<!--
	This is a SolarNode deployment configuration for plugins that use the Nifty SunSpec framework.
-->
<ivy-module version="2.0">
	<info organisation="SolarNetwork" module="SolarNode-Nifty-SunSpec"/>
	<configurations>
		<conf name="runtime" visibility="public" description="The Runtime"/>
	</configurations>
	<dependencies defaultconfmapping="runtime->default(runtime)">

		<dependency org="net.solarnetwork.common" name="nifty-sunspec-api" rev="0.1.0"/>
		<dependency org="net.solarnetwork.common" name="nifty-sunspec-core" rev="0.1.0"/>

		<exclude org="io.netty"/>
		<exclude org="org.jspecify"/>
		<exclude org="org.slf4j"/>

	</dependencies>
</ivy-module>
