#!/bin/sh -e

service_down () {
	name="$1"
	if systemctl is-enabled "$name" >/dev/null; then
		echo "Disabling $name..."
		systemctl disable --now "$name" || true
	fi
}

if [ "$1" = "remove" ]; then
	service_down sn-wifi-bootconf.service
	service_down sn-wifi-conf@wlan0.service
	service_down sn-wifi-conf@wlan0.path
	service_down sn-wifi-autoap-restore.service
	service_down sn-wifi-autoap@wlan0.service
	systemctl daemon-reload >/dev/null || true
fi
