#!/bin/sh -e

service_down () {
	name="$1"
	if systemctl is-enabled "$name" >/dev/null; then
		echo "Disabling $name..."
		systemctl disable --now "$name" || true
	fi
}

if [ "$1" = "remove" ]; then
	for f in `ls /etc/solarnode/socketcand/*.env`; do
		fname=${f##*/}
		service_down "socketcand@${fname%%.env}.service"
	done
	systemctl daemon-reload >/dev/null || true
elif [ "$1" = "purge" ]; then
	rm -f /etc/solarnode/socketcand/*.env
fi
